export default [
  {
    id: 1,
    img: "Group-3.svg",
    title: "W E L C O M E",
    h2: "Lorem ipsum dolor sit amet consectetur",
    p: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus iste?",
    input: "Explore",
    color: "text-black bg-white",
    flex: "sm:flex-row-reverse",
    margin: "xl:ml-20",
  },
  {
    id: 2,
    img: "Group-1.svg",
    title: "",
    h2: "Lorem ipsum dolor sit amet consectetur",
    p: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus iste?",
    input: "Learn More",
    color: "text-white bg-black",
    flex: "sm:flex-row",
    margin: "xl:mr-20",
  },
  {
    id: 3,
    img: "Group.svg",
    title: "",
    h2: "Lorem ipsum dolor sit amet consectetur",
    p: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus iste?",
    input: "Learn More",
    color: "text-white bg-black",
    flex: "sm:flex-row-reverse",
    margin: "xl:ml-20",
  },
];
